name: github pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: 
          lfs: true

      - name: "Install Python 3.10"
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      #- name: "Generate SUMMARY.md"
        #run: "python3 gen_summary.py"

      - name: Install mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: "Build site"
        run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
